### ISSUE TITLE
使用github的issue进行社区讨论

### ISSUE THREAD

**Issue by gelosie** [RustChina/rustchina.github.io#1]
如题，可行么？

**Comment by fantix** [comment]
@gelosie commented **5 days ago**

目测还差点火

**Comment by ghost** [comment]
人气不足阿

**Comment by wankai** [comment]
用这个域名搭建一个ruby-china.org一样的社区吧，rust1.0年底就快了，社区得跟上啊

**Comment by gelosie** [comment]
@fantix 
当下还没开始深入建社区

@wankai 
嗯，可有服务器资源？

**Comment by wankai** [comment]
服务器资源我看看。

这两天我写了一篇关于rust模块的文章，供大家指正 http://wankai.github.io/2014/09/26/rust-module-system.html

**Comment by fengsp** [comment]
暂时可行，刚刚找rust-china域名，发现已经被你抢注了，不过页面做的有些简陋呀:)
顺便提一个问题，现在rust安装包下载速度奇慢，可以拷贝一些放在国内。

**Comment by ghost** [comment]
我觉得可以进入Guide的翻译了。在有VPS的条件下，可以考虑使用iron搭建rust-china.org。一点建议：)

**Comment by wankai** [comment]
我这里有一台linode的机器，我们开始rust-china.org的设计和开发吧

**Comment by fengsp** [comment]
@wankai 赞

**Comment by fengsp** [comment]
我建立了一个邮件列表 https://groups.google.com/group/rust-cn

**Comment by fantix** [comment]
@fengsp 本来人就少，能合着做还是合着做吧：https://groups.google.com/forum/#!forum/rust-china

**Comment by gelosie** [comment]
@wankai   @geekcraik  我把 DNS 解释转到 linode 的 ip 吧，看看使用什么来建社区。

@fantix @fengsp 合着做好。目标都是在国内建立非盈利性推广 rust 的社区。

@All   rust-china.org 群 168474970

**Comment by wankai** [comment]
@All, 社区还是得用rust来开发，要不然说不过去，现在rust-china人还不是很多，我们有时间开发。
可以借鉴一下ruby社区、go社区，看看怎么设计rust-china.org
